version: '3.7'

services:
  rabbitmq-broker:
    container_name: rabbitmq-broker
    build:
      context: rabbitmq-broker/
      dockerfile: Dockerfile
      target: rabbitmq
    image: rabbitmq-broker:latest
    ports:
      - 15672:15672